# Generated by Django 3.1.12 on 2025-12-17 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id_candidato', models.CharField(help_text='Digite o CPF (apenas números ou com pontuação)', max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome_candidato', models.CharField(max_length=255)),
                ('nascimento_candidato', models.DateField()),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('peso_candidato', models.FloatField(blank=True, null=True)),
                ('religiao', models.CharField(blank=True, max_length=100, null=True)),
                ('velocidade_caminhada', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('moderada', 'Moderada'), ('alta', 'Alta')], max_length=20, null=True)),
                ('sexo_desejado_cao', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea'), ('indiferente', 'Indiferente')], max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Apto', 'Apto'), ('Inapto', 'Inapto')], default='Apto', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaoGuia',
            fields=[
                ('id_cao', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('nome_cao', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('nascimento_cao', models.DateField()),
                ('peso_cao', models.FloatField()),
                ('tamanho', models.FloatField()),
                ('inicio_treinamento', models.DateField()),
                ('termino_treinamento', models.DateField()),
                ('total_horas_treinadas', models.IntegerField()),
                ('treinador_responsavel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_usuario', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoDupla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('cao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.caoguia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.candidato')),
            ],
        ),
    ]
