# Generated by Django 3.1.12 on 2025-08-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id_candidato', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_candidato', models.CharField(max_length=255)),
                ('nascimento_candidato', models.DateField()),
                ('altura', models.FloatField()),
                ('peso_candidato', models.FloatField()),
                ('estado_civil', models.CharField(max_length=100)),
                ('religiao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Apto', 'Apto'), ('Inapto', 'Inapto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaoGuia',
            fields=[
                ('id_cao', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_cao', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('nascimento_cao', models.DateField()),
                ('peso_cao', models.FloatField()),
                ('tamanho', models.FloatField()),
                ('inicio_treinamento', models.DateField()),
                ('termino_treinamento', models.DateField()),
                ('total_horas_treinadas', models.IntegerField()),
                ('treinador_responsavel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_usuario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoDupla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('cao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.caoguia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.candidato')),
            ],
        ),
    ]
