# Generated by Django 3.1.12 on 2025-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacaodupla',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacaodupla',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
