# Generated by Django 3.1.12 on 2025-12-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caoguia',
            name='velocidade_caminhada',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('moderada', 'Moderada'), ('alta', 'Alta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caoguia',
            name='id_cao',
            field=models.CharField(help_text='Número de identificação único', max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='ID do Cão / Microchip'),
        ),
        migrations.AlterField(
            model_name='caoguia',
            name='inicio_treinamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caoguia',
            name='peso_cao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caoguia',
            name='tamanho',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='caoguia',
            name='termino_treinamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caoguia',
            name='total_horas_treinadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caoguia',
            name='treinador_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
