# Generated by Django 3.1.12 on 2025-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_mdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='teste',
            field=models.CharField(max_length=100),
        ),
    ]
