# Generated by Django 3.1.12 on 2025-10-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_mdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatoinformacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('velocidade_caminhada', models.CharField(max_length=50)),
                ('sexo_desejado_cao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caoinformacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('raca', models.CharField(max_length=100)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('velocidade_caminhada', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='teste',
        ),
    ]
