# Generated by Django 3.1.12 on 2025-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_mdb', '0002_auto_20251002_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caoinformacoes',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='caoinformacoes',
            name='raca',
        ),
        migrations.AddField(
            model_name='caoinformacoes',
            name='id_cao',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
