# Generated by Django 3.1.12 on 2025-12-31 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.candidato')),
                ('cao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.caoguia')),
            ],
        ),
    ]
